### ISSUE TITLE
Is there any way to grab the filtered values and export them to PDF or XLS?

### ISSUE THREAD

**Issue by angelinchaustipy** [protonemedia/inertiajs-tables-laravel-query-builder#29]
I am needing to export the records that are filtered in the table in XLS or PDF Format using Laravel and VueJS.

**Comment by wattsie** [comment]
This would be awesome. 
At a minimum CSV would be good (ie JsonCSV).

I do see a possible issue when exporting large amount of data.
Inertia seems to imposed a 640k limit (at least on firefox) as I keep getting NS_ERROR_ILLEGAL_VALUE when trying to access large datasets.

I expect, it may require a second controller, via an api style call (ie not rendered by Inertia) to pass all the data (axios etc).

Would be nice to pass the current filters and column status props so you can match what is being displayed.

Cheers.

**Comment by mUcHG0Di** [comment]
I made a controller for this using FastExcel. 
https://gist.github.com/mUcHG0Di/9d133aec56cfe98d3296bca0c64aad74

Instructions are commented in the gist, but in a few words:
- Create an extension of InteractsWithQueryBuilder.vue, to remove the following condition in method getColumnsForQuery:
```
if (enabledColumns.length === Object.keys(columns || {}).length) {
        return [];
}
```

- Import your new InteractsWithQueryBuilder file in your view, instead of the original one: 
`import InteractsWithQueryBuilder from '@/InteractsWithQueryBuilder';`

- Create a button or something, that executes the following:
```
const query = this.queryBuilderString; // The query
const url = route('excel.export'); // Your export route
const model = 'App\Models\Product'; // The model to export
window.location.href = `${url}?${query}&model=${model}`

```

- Add the route: Route::get('excel/export', \App\Http\Controllers
`\ExcelController::class)->name('excel.export')->prefix('excel');`

And it should work with no modifications.. In most cases :')

**Comment by pascalbaljet** [comment]
PDF/XLS exports are out of scope for this package, but I suggest looking at Laravel Excel. Maybe you could use the [Collection Export](https://docs.laravel-excel.com/3.1/exports/collection.html) feature.
